# TCL File Generated by Component Editor 10.1sp1
# Sat Jun 04 23:28:49 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | chu_avalon_gcd "chu_avalon_gcd" v1.0
# | p chu 2011.06.04.23:28:49
# | GCD hardware accelerator
# | 
# | K:/code/vlog_chu_ip_v101/chu_avalon_gcd/chu_avalon_gcd.v
# | 
# |    ./chu_avalon_gcd.v syn, sim
# |    ./gcd_engine.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module chu_avalon_gcd
# | 
set_module_property DESCRIPTION "GCD hardware accelerator"
set_module_property NAME chu_avalon_gcd
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP chu_vlog_ip
set_module_property AUTHOR "p chu"
set_module_property DISPLAY_NAME chu_avalon_gcd
set_module_property TOP_LEVEL_HDL_FILE chu_avalon_gcd.v
set_module_property TOP_LEVEL_HDL_MODULE chu_avalon_gcd
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file chu_avalon_gcd.v {SYNTHESIS SIMULATION}
add_file gcd_engine.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset_reset
# | 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT

set_interface_property clock_reset_reset ENABLED true

add_interface_port clock_reset_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point gcd
# | 
add_interface gcd avalon end
set_interface_property gcd addressAlignment DYNAMIC
set_interface_property gcd addressUnits WORDS
set_interface_property gcd associatedClock clock_reset
set_interface_property gcd associatedReset clock_reset_reset
set_interface_property gcd burstOnBurstBoundariesOnly false
set_interface_property gcd explicitAddressSpan 0
set_interface_property gcd holdTime 0
set_interface_property gcd isMemoryDevice false
set_interface_property gcd isNonVolatileStorage false
set_interface_property gcd linewrapBursts false
set_interface_property gcd maximumPendingReadTransactions 0
set_interface_property gcd printableDevice false
set_interface_property gcd readLatency 0
set_interface_property gcd readWaitStates 0
set_interface_property gcd readWaitTime 0
set_interface_property gcd setupTime 0
set_interface_property gcd timingUnits Cycles
set_interface_property gcd writeWaitTime 0

set_interface_property gcd ENABLED true

add_interface_port gcd gcd_address address Input 3
add_interface_port gcd gcd_chipselect chipselect Input 1
add_interface_port gcd gcd_write write Input 1
add_interface_port gcd gcd_writedata writedata Input 32
add_interface_port gcd gcd_readdata readdata Output 32
# | 
# +-----------------------------------
