
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module test_clase1(

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



ejem_mux multiplexor
(
	.sel(SW[1:0]) ,	// input [1:0] sel_sig
	.out() 	// output [7:0] out_sig
);


contador contador_inst
(
	.clk(FPGA_CLK1_50) ,	// input  clk_sig
	.reset(KEY[0]) ,	// input  reset_sig
	.conteo(LED[7:0]) 	// output [7:0] conteo_sig
);

syncro syncro_inst
(
	.async(async_sig) ,	// input  async_sig
	.clock(clock_sig) ,	// input  clock_sig
	.sync(sync_sig) 	// output  sync_sig
);


endmodule
