// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Sat Jun 11 10:30:46 2016

timer_ece10243upb2016 timer_ece10243upb2016_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.timer_address(timer_address_sig) ,	// input [2:0] timer_address_sig
	.timer_chipselect(timer_chipselect_sig) ,	// input  timer_chipselect_sig
	.timer_write(timer_write_sig) ,	// input  timer_write_sig
	.timer_writedata(timer_writedata_sig) ,	// input [31:0] timer_writedata_sig
	.timer_readdata(timer_readdata_sig) ,	// output [31:0] timer_readdata_sig
	.timer_irq(timer_irq_sig) ,	// output  timer_irq_sig
	.toggle(toggle_sig) 	// output  toggle_sig
);

