# TCL File Generated by Component Editor 10.1sp1
# Thu Jun 02 23:16:20 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | chu_avalon_div_demo "chu_avalon_div_demo" v1.0
# | p chu 2011.06.02.23:16:20
# | Component demo with division circuit
# | 
# | K:/code/vlog_chu_ip_v101/chu_avalon_div/chu_avalon_div_demo.v
# | 
# |    ./chu_avalon_div_demo.v syn, sim
# |    ./div.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module chu_avalon_div_demo
# | 
set_module_property DESCRIPTION "Component demo with division circuit"
set_module_property NAME chu_avalon_div_demo
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP chu_vlog_ip
set_module_property AUTHOR "p chu"
set_module_property DISPLAY_NAME chu_avalon_div_demo
set_module_property TOP_LEVEL_HDL_FILE chu_avalon_div_demo.v
set_module_property TOP_LEVEL_HDL_MODULE chu_avalon_div_demo
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file chu_avalon_div_demo.v {SYNTHESIS SIMULATION}
add_file div.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter W INTEGER 32
set_parameter_property W DEFAULT_VALUE 32
set_parameter_property W DISPLAY_NAME W
set_parameter_property W TYPE INTEGER
set_parameter_property W UNITS None
set_parameter_property W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property W AFFECTS_GENERATION false
set_parameter_property W HDL_PARAMETER true
add_parameter CBIT INTEGER 6
set_parameter_property CBIT DEFAULT_VALUE 6
set_parameter_property CBIT DISPLAY_NAME CBIT
set_parameter_property CBIT TYPE INTEGER
set_parameter_property CBIT UNITS None
set_parameter_property CBIT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CBIT AFFECTS_GENERATION false
set_parameter_property CBIT HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point div_cpu
# | 
add_interface div_cpu avalon end
set_interface_property div_cpu addressAlignment DYNAMIC
set_interface_property div_cpu addressUnits WORDS
set_interface_property div_cpu associatedClock clock
set_interface_property div_cpu associatedReset reset_sink
set_interface_property div_cpu burstOnBurstBoundariesOnly false
set_interface_property div_cpu explicitAddressSpan 0
set_interface_property div_cpu holdTime 0
set_interface_property div_cpu isMemoryDevice false
set_interface_property div_cpu isNonVolatileStorage false
set_interface_property div_cpu linewrapBursts false
set_interface_property div_cpu maximumPendingReadTransactions 0
set_interface_property div_cpu printableDevice false
set_interface_property div_cpu readLatency 0
set_interface_property div_cpu readWaitStates 0
set_interface_property div_cpu readWaitTime 0
set_interface_property div_cpu setupTime 0
set_interface_property div_cpu timingUnits Cycles
set_interface_property div_cpu writeWaitTime 0

set_interface_property div_cpu ENABLED true

add_interface_port div_cpu div_chipselect chipselect Input 1
add_interface_port div_cpu div_write write Input 1
add_interface_port div_cpu div_address address Input 3
add_interface_port div_cpu div_readdata readdata Output W
add_interface_port div_cpu div_writedata writedata Input W
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point div_intr
# | 
add_interface div_intr interrupt end
set_interface_property div_intr associatedAddressablePoint div_cpu
set_interface_property div_intr associatedClock clock
set_interface_property div_intr associatedReset reset_sink

set_interface_property div_intr ENABLED true

add_interface_port div_intr div_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point div_ledg
# | 
add_interface div_ledg conduit end

set_interface_property div_ledg ENABLED true

add_interface_port div_ledg div_led export Output 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------
