# TCL File Generated by Component Editor 10.1sp1
# Sat Jun 04 23:30:48 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | chu_avalon_frac "chu_avalon_frac" v1.0
# | p chu 2011.06.04.23:30:48
# | Fractal hardware accelerator
# | 
# | K:/code/vlog_chu_ip_v101/chu_avalon_frac/chu_avalon_frac.v
# | 
# |    ./chu_avalon_frac.v syn, sim
# |    ./frac_engine.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module chu_avalon_frac
# | 
set_module_property DESCRIPTION "Fractal hardware accelerator"
set_module_property NAME chu_avalon_frac
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP chu_vlog_ip
set_module_property AUTHOR "p chu"
set_module_property DISPLAY_NAME chu_avalon_frac
set_module_property TOP_LEVEL_HDL_FILE chu_avalon_frac.v
set_module_property TOP_LEVEL_HDL_MODULE chu_avalon_frac
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file chu_avalon_frac.v {SYNTHESIS SIMULATION}
add_file frac_engine.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset_reset
# | 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT

set_interface_property clock_reset_reset ENABLED true

add_interface_port clock_reset_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point frac_cpu
# | 
add_interface frac_cpu avalon end
set_interface_property frac_cpu addressAlignment DYNAMIC
set_interface_property frac_cpu addressUnits WORDS
set_interface_property frac_cpu associatedClock clock_reset
set_interface_property frac_cpu associatedReset clock_reset_reset
set_interface_property frac_cpu burstOnBurstBoundariesOnly false
set_interface_property frac_cpu explicitAddressSpan 0
set_interface_property frac_cpu holdTime 0
set_interface_property frac_cpu isMemoryDevice false
set_interface_property frac_cpu isNonVolatileStorage false
set_interface_property frac_cpu linewrapBursts false
set_interface_property frac_cpu maximumPendingReadTransactions 0
set_interface_property frac_cpu printableDevice false
set_interface_property frac_cpu readLatency 0
set_interface_property frac_cpu readWaitStates 0
set_interface_property frac_cpu readWaitTime 0
set_interface_property frac_cpu setupTime 0
set_interface_property frac_cpu timingUnits Cycles
set_interface_property frac_cpu writeWaitTime 0

set_interface_property frac_cpu ENABLED true

add_interface_port frac_cpu frac_address address Input 2
add_interface_port frac_cpu frac_chipselect chipselect Input 1
add_interface_port frac_cpu frac_write write Input 1
add_interface_port frac_cpu frac_writedata writedata Input 32
add_interface_port frac_cpu frac_readdata readdata Output 32
# | 
# +-----------------------------------
