
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module test_clase1(

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



ejem_mux multiplexor
(
	.sel(SW[1:0]) ,	// input [1:0] sel_sig
	.out(LED[7:0]) 	// output [7:0] out_sig
);




endmodule
