# TCL File Generated by Component Editor 10.1sp1
# Sat Jun 04 23:33:00 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | chu_avalon_audio "chu_avalon_audio" v1.0
# | p chu 2011.06.04.23:33:00
# | codec and i2c controller
# | 
# | K:/code/vlog_chu_ip_v101/chu_avalon_audio/chu_avalon_audio.v
# | 
# |    ./chu_avalon_audio.v syn, sim
# |    ./codec_top.v syn, sim
# |    ./adc_dac.v syn, sim
# |    ./i2c.v syn, sim
# |    ./K:/code/vlog_chu_ip_v101/chu_avalon_fifo/fifo_ctrl.v syn, sim
# |    ./K:/code/vlog_chu_ip_v101/chu_avalon_fifo/fifo_top.v syn, sim
# |    ./K:/code/vlog_chu_ip_v101/chu_avalon_fifo/reg_file.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module chu_avalon_audio
# | 
set_module_property DESCRIPTION "codec and i2c controller"
set_module_property NAME chu_avalon_audio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP chu_vlog_ip
set_module_property AUTHOR "p chu"
set_module_property DISPLAY_NAME chu_avalon_audio
set_module_property TOP_LEVEL_HDL_FILE chu_avalon_audio.v
set_module_property TOP_LEVEL_HDL_MODULE chu_avalon_audio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file chu_avalon_audio.v {SYNTHESIS SIMULATION}
add_file codec_top.v {SYNTHESIS SIMULATION}
add_file adc_dac.v {SYNTHESIS SIMULATION}
add_file i2c.v {SYNTHESIS SIMULATION}
add_file K:/code/vlog_chu_ip_v101/chu_avalon_fifo/fifo_ctrl.v {SYNTHESIS SIMULATION}
add_file K:/code/vlog_chu_ip_v101/chu_avalon_fifo/fifo_top.v {SYNTHESIS SIMULATION}
add_file K:/code/vlog_chu_ip_v101/chu_avalon_fifo/reg_file.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter FIFO_SIZE INTEGER 3
set_parameter_property FIFO_SIZE DEFAULT_VALUE 3
set_parameter_property FIFO_SIZE DISPLAY_NAME FIFO_SIZE
set_parameter_property FIFO_SIZE TYPE INTEGER
set_parameter_property FIFO_SIZE UNITS None
set_parameter_property FIFO_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_SIZE AFFECTS_GENERATION false
set_parameter_property FIFO_SIZE HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset_reset
# | 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT

set_interface_property clock_reset_reset ENABLED true

add_interface_port clock_reset_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point codec_io
# | 
add_interface codec_io conduit end

set_interface_property codec_io ENABLED true

add_interface_port codec_io m_clk export Output 1
add_interface_port codec_io b_clk export Output 1
add_interface_port codec_io dac_lr_clk export Output 1
add_interface_port codec_io adc_lr_clk export Output 1
add_interface_port codec_io dacdat export Output 1
add_interface_port codec_io adcdat export Input 1
add_interface_port codec_io i2c_sclk export Output 1
add_interface_port codec_io i2c_sdat export Bidir 1
add_interface_port codec_io codec_adc_rd export Input 1
add_interface_port codec_io codec_adc_data_out export Output 32
add_interface_port codec_io codec_dac_wr export Input 1
add_interface_port codec_io codec_dac_data_in export Input 32
add_interface_port codec_io codec_sample_tick export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point cpu_codec
# | 
add_interface cpu_codec avalon end
set_interface_property cpu_codec addressAlignment DYNAMIC
set_interface_property cpu_codec addressUnits WORDS
set_interface_property cpu_codec associatedClock clock_reset
set_interface_property cpu_codec associatedReset clock_reset_reset
set_interface_property cpu_codec burstOnBurstBoundariesOnly false
set_interface_property cpu_codec explicitAddressSpan 0
set_interface_property cpu_codec holdTime 0
set_interface_property cpu_codec isMemoryDevice false
set_interface_property cpu_codec isNonVolatileStorage false
set_interface_property cpu_codec linewrapBursts false
set_interface_property cpu_codec maximumPendingReadTransactions 0
set_interface_property cpu_codec printableDevice false
set_interface_property cpu_codec readLatency 0
set_interface_property cpu_codec readWaitStates 0
set_interface_property cpu_codec readWaitTime 0
set_interface_property cpu_codec setupTime 0
set_interface_property cpu_codec timingUnits Cycles
set_interface_property cpu_codec writeWaitTime 0

set_interface_property cpu_codec ENABLED true

add_interface_port cpu_codec audio_address address Input 2
add_interface_port cpu_codec audio_chipselect chipselect Input 1
add_interface_port cpu_codec audio_write write Input 1
add_interface_port cpu_codec audio_writedata writedata Input 32
add_interface_port cpu_codec audio_read read Input 1
add_interface_port cpu_codec audio_readdata readdata Output 32
# | 
# +-----------------------------------
