# TCL File Generated by Component Editor 10.1sp1
# Thu Jun 02 23:12:39 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | chu_avalon_sram "chu_avalon_sram" v1.0
# | p chu 2011.06.02.23:12:39
# | 
# | 
# | K:/code/vlog_chu_ip_v101/chu_avalon_sram/chu_avalon_sram.v
# | 
# |    ./chu_avalon_sram.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module chu_avalon_sram
# | 
set_module_property NAME chu_avalon_sram
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP chu_vlog_ip
set_module_property AUTHOR "p chu"
set_module_property DISPLAY_NAME chu_avalon_sram
set_module_property TOP_LEVEL_HDL_FILE chu_avalon_sram.v
set_module_property TOP_LEVEL_HDL_MODULE chu_avalon_sram
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file chu_avalon_sram.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point cpu_ctrl
# | 
add_interface cpu_ctrl avalon end
set_interface_property cpu_ctrl addressAlignment DYNAMIC
set_interface_property cpu_ctrl addressUnits WORDS
set_interface_property cpu_ctrl associatedClock clock
set_interface_property cpu_ctrl associatedReset reset
set_interface_property cpu_ctrl burstOnBurstBoundariesOnly false
set_interface_property cpu_ctrl explicitAddressSpan 0
set_interface_property cpu_ctrl holdTime 0
set_interface_property cpu_ctrl isMemoryDevice true
set_interface_property cpu_ctrl isNonVolatileStorage false
set_interface_property cpu_ctrl linewrapBursts false
set_interface_property cpu_ctrl maximumPendingReadTransactions 0
set_interface_property cpu_ctrl printableDevice false
set_interface_property cpu_ctrl readLatency 2
set_interface_property cpu_ctrl readWaitStates 0
set_interface_property cpu_ctrl readWaitTime 0
set_interface_property cpu_ctrl setupTime 0
set_interface_property cpu_ctrl timingUnits Cycles
set_interface_property cpu_ctrl writeWaitTime 0

set_interface_property cpu_ctrl ENABLED true

add_interface_port cpu_ctrl address address Input 18
add_interface_port cpu_ctrl chipselect_n chipselect_n Input 1
add_interface_port cpu_ctrl read_n read_n Input 1
add_interface_port cpu_ctrl write_n write_n Input 1
add_interface_port cpu_ctrl byteenable_n byteenable_n Input 2
add_interface_port cpu_ctrl writedata writedata Input 16
add_interface_port cpu_ctrl readdata readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point sram_addr
# | 
add_interface sram_addr conduit end

set_interface_property sram_addr ENABLED true

add_interface_port sram_addr sram_dq export Bidir 16
add_interface_port sram_addr sram_ce_n export Output 1
add_interface_port sram_addr sram_oe_n export Output 1
add_interface_port sram_addr sram_we_n export Output 1
add_interface_port sram_addr sram_lb_n export Output 1
add_interface_port sram_addr sram_ub_n export Output 1
add_interface_port sram_addr sram_addr export Output 18
# | 
# +-----------------------------------
